AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Enabled: true
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  EnforcedStyle: template
